#!/usr/bin/env python

# https://github.com/goodguyry/bella
# Global configuration file
# Served from home directory
# If not present in the user's home directory,
#   all configuration setting must be in bella.config

{

  'defaults': {
    'environment': 'develop',
    'precision': 4,
    'watchFile': 'core',
    'addMinToFilename': True,
    'addMaxToFilename': True
  },

  'develop': {
    'style': 'expanded',
    'lineNumbers': True
  },

  'deploy': {
    'style': 'compressed',
    'lineNumbers': False
  }

}
