#!/usr/bin/env python

# Global file, served from home directory

# Bella global environments and default settings
#    bella.config in site's root directory takes precedence

{

  'defaults': {
    'environment': 'develop',
    'precision': 4,
    'watchFile': 'core',
    'addMinToFilename': True,
    'addMaxToFilename': True
  },

  'develop': {
    'style': 'expanded',
    'lineNumbers': True
  },

  'deploy': {
    'style': 'compressed',
    'lineNumbers': False
  }

}
